export const data = Object.freeze({
  characters: [
    {
      teamname: "Besaid Aurochs",
      key: "1",
      image: "/images/Tidus_blitzball.webp",
      image_height: 200,
      image_width: 72,
      name: "Tidus",
      techniques: "Venom Tackle, Drain Tackle, Anti-Venom 2",
      location: "N/A",
    },
    {
      teamname: "Besaid Aurochs",
      key: "2",
      image: "/images/Datto.webp",
      image_height: 200,
      image_width: 87,
      name: "Datto",
      techniques: "Wither Shot, Anti-Venom, Wither Shot 2",
      location: "Luca Stadium - Aurochs Locker Room",
    },
    {
      teamname: "Besaid Aurochs",
      key: "3",
      image: "/images/Letty.webp",
      image_height: 200,
      image_width: 60,
      name: "Letty",
      techniques: "Wither Tackle, Nap Pass, Venom Pass 3",
      location: "Luca Stadium - Aurochs Locker Room",
    },
    {
      teamname: "Besaid Aurochs",
      key: "4",
      image: "/images/Jassu.webp",
      image_height: 200,
      image_width: 91,
      name: "Jassu",
      techniques: "Wither Tackle, Wither Tackle 2, Nap Tackle 2",
      location: "Luca Stadium - Aurochs Locker Room",
    },
    {
      teamname: "Besaid Aurochs",
      key: "5",
      image: "/images/Botta.webp",
      image_height: 200,
      image_width: 75,
      name: "Botta",
      techniques: "Venom Shot, Venom Pass 2, Nap Tackle",
      location: "Luca Stadium - Aurochs Locker Room",
    },
    {
      teamname: "Besaid Aurochs",
      key: "6",
      image: "/images/Keepa.webp",
      image_height: 200,
      image_width: 87,
      name: "Keepa",
      techniques: "Super Goalie, Volley Shoot, Anti-Wither",
      location: "Luca Stadium - Aurochs Locker Room",
    },
    {
      teamname: "Kilika Beasts",
      key: "1",
      image: "/images/Larbeight.jpg",
      image_height: 200,
      image_width: 74,
      name: "Larbeight",
      techniques: "Wither Shot, Anit-Nap, Tackle Slip 2",
      location: "Kilika Port - Docks",
    },
    {
      teamname: "Kilika Beasts",
      key: "2",
      image: "/images/Isken.jpg",
      image_height: 200,
      image_width: 78,
      name: "Isken",
      techniques: "Wither Pass, Wither Tackle, Wither Tackle 2",
      location: "Kilika Port - House",
    },
    {
      teamname: "Kilika Beasts",
      key: "3",
      image: "/images/Vuroja.jpg",
      image_height: 200,
      image_width: 95,
      name: "Vuroja",
      techniques: "Wither Tackle, Nap Pass, Anti-Nap",
      location: "Kilika Port - Docks",
    },
    {
      teamname: "Kilika Beasts",
      key: "4",
      image: "/images/Kulukan.webp",
      image_height: 200,
      image_width: 80,
      name: "KuluKan",
      techniques: "Drain Tackle, Nap Pass, Venom Tackle 3",
      location: "Kilika Port - Tavern",
    },
    {
      teamname: "Kilika Beasts",
      key: "5",
      image: "/images/Deim.webp",
      image_height: 200,
      image_width: 56,
      name: "Deim",
      techniques: "Venom Tackle, Wither Pass, Pile Wither",
      location: "Kilika Port - Great Hall",
    },
    {
      teamname: "Kilika Beasts",
      key: "6",
      image: "/images/Nizarut.webp",
      image_height: 200,
      image_width: 70,
      name: "Nizarut",
      techniques: "Venom Shot, Anti-Wither, Anti-Nap",
      location: "Kilika Port - Great Hall",
    },
    {
      teamname: "Luca Goers",
      key: "1",
      image: "/images/Bickson.webp",
      image_height: 200,
      image_width: 89,
      name: "Bickson",
      techniques: "Wither Shot, Nap Pass, Anti-Nap",
      location: "Luca Harbor - Number 3 Dock",
    },
    {
      teamname: "Luca Goers",
      key: "2",
      image: "/images/Abus.webp",
      image_height: 200,
      image_width: 64,
      name: "Abus",
      techniques: "Grip Gloves, Venom Tackle 2, Venom Shot 3",
      location: "Luca Harbor - Number 3 Dock",
    },
    {
      teamname: "Luca Goers",
      key: "3",
      image: "/images/Graav.webp",
      image_height: 200,
      image_width: 92,
      name: "Graav",
      techniques: "Venom Pass, Tackle Slip, Drain Tackle 2",
      location: "Luca Harbor - Number 3 Dock",
    },
    {
      teamname: "Luca Goers",
      key: "4",
      image: "/images/Doram.webp",
      image_height: 200,
      image_width: 93,
      name: "Doram",
      techniques: "Wither Tackle, Nap Tackle, Volley Shot",
      location: "Luca Harbor - Number 3 Dock",
    },
    {
      teamname: "Luca Goers",
      key: "5",
      image: "/images/Balgerda.webp",
      image_height: 200,
      image_width: 52,
      name: "Balgerda",
      techniques: "Nap Tackle, Anti-Wither, Drain Tackle",
      location: "Luca Harbor - Number 3 Dock",
    },
    {
      teamname: "Luca Goers",
      key: "6",
      image: "/images/Raudy.jpg",
      image_height: 200,
      image_width: 67,
      name: "Raudy",
      techniques: "Grip Gloves, Gamble, Tackle Slip 2",
      location: "Luca Harbor - Number 3 Dock",
    },
    {
      teamname: "Al Bhed Psyches",
      key: "1",
      image: "/images/Eigaar.webp",
      image_height: 200,
      image_width: 70,
      name: "Eigaar",
      techniques: "Venom Tackls, Spin Ball, Volley Shot 3",
      location: "Airship - Corridor",
    },
    {
      teamname: "Al Bhed Psyches",
      key: "2",
      image: "/images/Blappa.webp",
      image_height: 200,
      image_width: 61,
      name: "Blappa",
      techniques: "Elite Defense, Drain Tackle, Nap Shot",
      location: "Airship - Corridor",
    },
    {
      teamname: "Al Bhed Psyches",
      key: "3",
      image: "/images/Berrik.webp",
      image_height: 200,
      image_width: 93,
      name: "Berrik",
      techniques: "Venom Tackle, Wither Tackle 2, Elite Defense",
      location: "Airship - Corridor",
    },
    {
      teamname: "Al Bhed Psyches",
      key: "4",
      image: "/images/Judda.webp",
      image_height: 200,
      image_width: 84,
      name: "Judda",
      techniques: "Anti-Nap, Wither Tackle, Anti-Wither",
      location: "Airship - Corridor",
    },
    {
      teamname: "Al Bhed Psyches",
      key: "5",
      image: "/images/Lakkam.webp",
      image_height: 200,
      image_width: 51,
      name: "Lakkam",
      techniques: "Venom Tackle, Nap Pass, Tackle Slip",
      location: "Airship - Corridor",
    },
    {
      teamname: "Al Bhed Psyches",
      key: "6",
      image: "/images/Nimrook.webp",
      image_height: 200,
      image_width: 62,
      name: "Nimrook",
      techniques: "Vemon Tackle, Venom Tackle 2, Anti-Drain",
      location: "Airship - Corridor",
    },
  ],
});

export const get_characters_by_teamname = (teamname) => {
  return data.characters
    .filter((character) => character.teamname === teamname)
    .sort((a, b) => a.key - b.key);
};

export const get_team_by_teamname = (teamname) => {
  return data.characters.filter((team) => team.name == teamname).at(0);
};
