export const data = Object.freeze({
  aeons: [
    {
      role: "Aeon",
      key: "1",
      image: "/images/Valefor.jpeg",
      image_height: 400,
      image_width: 513,
      name: "Valefor",
      description:
        "An arieal aeon with great wings whose fayth statue is located in Besaid Temple.",
      location: "Besaid Temple",
    },
    {
      role: "Aeon",
      key: "2",
      image: "/images/Ifrit.jpg",
      image_height: 400,
      image_width: 413,
      name: "Ifrit",
      description:
        "A demon that holds dominion over fire, with a fayth statue situated in Kilika Temple.",
      location: "Kilika Temple",
    },
    {
      role: "Aeon",
      key: "3",
      image: "/images/Ixion.jpg",
      image_height: 400,
      image_width: 482,
      name: "Ixion",
      description:
        "A horned beast covered by lightning whose fayth statue stands in Djose Temple.",
      location: "Djose Temple",
    },
    {
      role: "Aeon",
      key: "4",
      image: "/images/Shiva.jpg",
      image_height: 400,
      image_width: 378,
      name: "Shiva",
      description:
        "The frozen queen of ice whose fayth statue is situated inside Macalania Temple.",
      location: "Macalania Temple",
    },
    {
      role: "Aeon",
      key: "5",
      image: "/images/Bahamut.jpg",
      image_height: 400,
      image_width: 380,
      name: "Bahamut",
      description:
        "A four-winged sacred dragon beast with a fayth statue located in Bevelle.",
      location: "Bevelle Temple",
    },
    {
      role: "Aeon",
      key: "6",
      image: "/images/Yojimbo.jpeg",
      image_height: 400,
      image_width: 457,
      name: "Yojimbo",
      description:
        "A master swordsman whose fayth statue is situated in the Cavern of the Stolen Fayth.",
      location: "Cavern of the Stolen Fayth",
    },
    {
      role: "Aeon",
      key: "7",
      image: "/images/Anima.jpeg",
      image_height: 400,
      image_width: 358,
      name: "Anima",
      description:
        "An aeon bound in heavy chains whose fayth statue can be found in the temple of Yevon-Baaj.",
      location: "Temple of Yevon-Baaj",
    },
    {
      role: "Aeon",
      key: "8",
      image: "/images/Magus_Sisters.jpeg",
      image_height: 400,
      image_width: 419,
      name: "Magus Sisters",
      description:
        "Three sister aeons whose fayth statue is situated in Remiem Temple.",
      location: "Remiem Temple",
    },
  ],
  characters: [
    {
      role: "Main Characters",
      key: "1",
      image: "/images/Tidus.jpg",
      image_height: 400,
      image_width: 363,
      name: "Tidus",
      description:
        "The optimistic crybaby who gives hope to a world gripped in the spiral of death. The son of Jecht, a blitzball legend, Tidus rebelled against his father from an early age.",
      link: "../characters/tidus",
    },
    {
      role: "Main Characters",
      key: "2",
      image: "/images/Yuna.jpg",
      image_height: 400,
      image_width: 363,
      name: "Yuna",
      description:
        "The summoner possessing endless kindness, willing to sacrifice herself to save the world. Daughter of High Summoner Braska.",
      link: "../characters/yuna",
    },
    {
      role: "Main Characters",
      key: "3",
      image: "/images/Auron.jpg",
      image_height: 400,
      image_width: 345,
      name: "Auron",
      description:
        "The legendary guardian who guides a young man to fulfill a promise to a friend. A man tasked with watching over Tidus in Dream Zanarkand who created the opportunity for Tidus to venture to Spira.",
      link: "../characters/auron",
    },
    {
      role: "Main Characters",
      key: "4",
      image: "/images/Kimahri.jpg",
      image_height: 400,
      image_width: 408,
      name: "Kimahri",
      description:
        "The hornless Ronso youth dedicating his life to Yuna. A Ronso who serves as Yuna's first guardian.",
      link: "../characters/kimahri",
    },
    {
      role: "Main Characters",
      key: "5",
      image: "/images/Wakka.jpg",
      image_height: 400,
      image_width: 290,
      name: "Wakka",
      description:
        "A good-natured older-brother type who has dedicated his youth to blitzball. The young coach and most valuable player of Besaid Village's blitzball team, the Besaid Aurochs.",
      link: "../characters/wakka",
    },
    {
      role: "Main Characters",
      key: "6",
      image: "/images/Lulu.jpg",
      image_height: 400,
      image_width: 313,
      name: "Lulu",
      description:
        "The severe yet sweet Black Mage who aids her comrades with a wealth of knowledge. A female Black Mage acting as Yuna's guardian who watches over her like a big sister.",
      link: "../characters/lulu",
    },
    {
      role: "Main Characters",
      key: "7",
      image: "/images/Rikku.jpg",
      image_height: 400,
      image_width: 265,
      name: "Rikku",
      description:
        "A hearty and hard-working Al Bhed lass, constantly thinking about what she can accomplish. Daughter to the chief of the Al Bhed, a tribe of people persecuted for opposing the teachings of Yevon, Rikku is also Yuna's cousin on her mother's side.",
      link: "../characters/rikku",
    },
    {
      role: "Supporting Characters",
      key: "1",
      image: "/images/Seymour.webp",
      image_height: 400,
      image_width: 400,
      name: "Seymour",
      description:
        "Seymour is the son of Jyscal, who became leader of theGuado, and a human woman.",
    },
  ],
  locations: [
    {
      name: "Dream Zanarkand",
      key: "1",
      image: "/images/Dream_Zanarkand.jpg",
      image_height: 400,
      image_width: 554,
      description:
        "The mechanical metropolis in which Tidus grew up. This city is actually a dream summoned by Yu Yevon, who sought to reproduce Zanarkand and its people as they existed a thousand years ago. In early development the city was called Registan.",
    },
    {
      name: "Submerged Ruins - Temple of Yevon-Baaj",
      key: "2",
      image: "/images/Yevon-Baaj.jpg",
      image_height: 400,
      image_width: 532,
      description:
        "The ruins of a Yevon temple destroyed by Sin decades earlier, Seymour lived here as a youth in the care of his mother, and in this temple's Chamber of the Fayth the youth Guado installed a statue representing Anima's Fayth.",
    },
    {
      name: "Salvage Ship",
      key: "3",
      image: "/images/Salvage_Ship.jpg",
      image_height: 400,
      image_width: 710,
      description:
        "A ship that belongs to the Al Bhed. It is used to go diving in ruins for machina. Brother is the leader of the ship. You visit this ship just once in the game, and you go on a salvage hunt with Rikku and her crew.",
    },
    {
      name: "Besaid Island",
      key: "4",
      image: "/images/Besaid_Island.jpg",
      image_height: 400,
      image_width: 596,
      description:
        "An island on the southern tip of Spira. It is a place abundant with nature. Its mountain regions are overgrown and with thick vegetation, broken up by a number of free-flowing waterfalls. Yuna and Wakka grew up in the elevated settlement of Besaid Island.",
    },
    {
      name: "S.S. Liki",
      key: "5",
      image: "/images/S.S._Liki.webp",
      image_height: 400,
      image_width: 711,
      description:
        "The ship that ferries people between the islands of Besaid and Kilika. It is powered by chocobos and sails.",
    },
    {
      name: "Kilika Island",
      key: "6",
      image: "/images/Kilika_Island.webp",
      image_height: 400,
      image_width: 579,
      description:
        "An island to the northwest of Besaid Island. Its residents reside in Kilika Port, a community built in the shallows. Lying just beyond the forest, Kilika Temple is well known as a spot where players can pray for a victory in blitzball.",
    },
    {
      name: "S.S. Winno",
      key: "7",
      image: "/images/S.S._Winno.webp",
      image_height: 400,
      image_width: 537,
      description:
        "The ship that ferries people between the island of Kilika and the city of Luca. This is where you perform the Jecht Shot for the first time. There is also a mini game that unlocks after you complete the Cloister of Trials at the Djose Temple. Return there and talk the woman at the top of the stairs, she will ask you how many seagulls are flying around. Tell her there are 11 total and she will gift you with the Ace Wizard weapon.",
    },
    {
      name: "Luca",
      key: "8",
      image: "/images/Luca.jpg",
      image_height: 400,
      image_width: 712,
      description:
        "The second largest city in Spira, it is famed for its massive blitzball stadium and a theater that plays movies and music. Luca has its own unique character, and teams of all races and cultures come to participate in its blitzball tournaments.",
    },
    {
      name: "Mi'ihen Highroad",
      key: "9",
      image: "/images/Mi'ihen_Highroad.jpg",
      image_height: 400,
      image_width: 578,
      description:
        "A highway famously walked by the hero Mi'ihen eight hundred years in the past. The Hero was the founder of the Crusaders and he has a statue on the Highroad. Part of the road was destroyed by Sin five hundred years ago, but a new road was built in its place. Along this highway, travelers can rent chocobos and find lodging at the Agency.",
    },
    {
      name: "Mushroom Rock",
      key: "10",
      image: "/images/Mushroom_Rock.jpg",
      image_height: 400,
      image_width: 574,
      description:
        "A highway connected to the northern tip of the Mi'ihen Highroad. The surrounding rockface resembles a pile of mushrooms; hence the name. The highway eventually forks, with one path leading to the highlands and the other to the Djose Highroad.",
    },
    {
      name: "Djose Temple",
      key: "11",
      image: "/images/Djose_Temple.jpg",
      image_height: 400,
      image_width: 704,
      description:
        "A region located to the south of central Spira. The Djose Highroad is know for the wind-eroded cliffs running through the coastlines. Many people visit the Djose Temple while traveling the highway, praying for a safe return.",
    },
    {
      name: "Moonflow",
      key: "12",
      image: "/images/Moonflow.png",
      image_height: 400,
      image_width: 533,
      description:
        "A large river that crosses the continent from north to south, filled with sunken ruins from a vanished era of technological civilization. When the purple moonlilies along the riverbank are in full bloom, they attract countless pyreflies during the night hours. The Hypello people ride domestic creatures known as shoopufs, ferrying passengers from one side of the river to the other.",
    },
    {
      name: "Guadosalam",
      key: "13",
      image: "/images/Guadosalam.jpg",
      image_height: 400,
      image_width: 711,
      description:
        "The city of the demihuman Guado people. Seymour's mansion is here, as is a mystical area replete with pyreflies that is known as the Farplane. Specters of the deceased appear in the Farplane when summoned by the living, resulting in many visitors who come to reunite with their loved ones.",
    },
    {
      name: "Farplane",
      key: "14",
      image: "/images/Farplane.webp",
      image_height: 400,
      image_width: 639,
      description:
        "An underworld, it is a gathering place for the dead. Spirits enter the Farplane either after they have been sent by one like a summoner or a sender, or after they have accepted their death. Those not sent to the Farplane may remain on the mortal plane as the unsent or fiends, both types able to send themselves by fulfilling a purpose failed to do in life.",
    },
    {
      name: "Thunder Plains",
      key: "15",
      image: "/images/Thunder_Plains.jpg",
      image_height: 400,
      image_width: 300,
      description:
        "A dangerous wasteland where rain and lightning are constantly released from the dark clouds that blanket the sky. In the past, travelers often lost their lives to lightning strikes while crossing the Thunder Plains, until an Al Bhed named Bilghen installed lightning rods that greatly increased the odds of safe passage.",
    },
    {
      name: "Macalania",
      key: "16",
      image: "/images/Macalania.jpg",
      image_height: 400,
      image_width: 285,
      description:
        "A shimmering forest can be found in the region, as well as a lake frozen over by the fayth in the local temple. The Macalania Woods connect to Bevelle and the Calm Lands, and the spheres in the middle of the forest gushes water dense with pyreflies, the raw material used in spheres.",
    },
    {
      name: "Bikanel Island",
      key: "17",
      image: "/images/Bikanel_Island.webp",
      image_height: 400,
      image_width: 606,
      description:
        "A large island to the west of the main continent, largely covered in desert. Due to a lack of visitors, the Al Bhed that had been persecuted by the temples of Yevon were able to establish the city of Home in secret. One corner of the island is home to Cactuars.",
    },
    {
      name: "Home",
      key: "18",
      image: "/images/Home.jpg",
      image_height: 400,
      image_width: 522,
      description:
        "It is the home of the Al Bhed clan located on Bikanel Island. It is an underground fortress hidden amid the Bikanel desert. It was built under Cid's direction to be the home of the Al Bhed, whom a lot fo the rest of Spira despise for not following the teachings of Yevon. This is where the Al Bhed house the kidnapped summoners they hold to save them from their fate.",
    },
    {
      name: "Bevelle",
      key: "19",
      image: "/images/Bevelle.webp",
      image_height: 400,
      image_width: 569,
      description:
        "The largest city in all of Spira, Bevelle is the cradle of Yevon's teachings, and the head temple of Yevon sits proudly in the middle of the city. The city's defenses are strict. No on can enter without passing over the Highbridge.",
    },
    {
      name: "Calm Lands",
      key: "20",
      image: "/images/Calm_Lands.jpg",
      image_height: 400,
      image_width: 597,
      description:
        "The plain where high summoners across multiple generations challenged Sin in order to bring about the temporary peace of Calm. To the east is a monster training facility for Crusaders established by the hero Mi'ihen, while the north lies the Cavern of the Stolen Fayth.",
    },
    {
      name: "Mt. Gagazet",
      key: "21",
      image: "/images/Mt_Gagazet.jpg",
      image_height: 400,
      image_width: 542,
      description:
        "A sacred mountain in the north of Spira, protected by the Ronso tribe. Harsh blizzards sweep the snowy mountain trial, sapping the strength of anyone brave enough to walk its path. Figures of the fayth, used to summon Dream Zanarkand, line the summit cliffs.",
    },
    {
      name: "Zanarkand Ruins",
      key: "22",
      image: "/images/Zanarkand_Ruins.png",
      image_height: 400,
      image_width: 572,
      description:
        "The relics of a city destroyed a thousand years ago, located in the northernmost tip of the continent. The fayth of the Final Summoning rests here, offering the ability to defeat Sin. Hopeful summoners treat the ruins as their final destination on their pilgrimage.",
    },
    {
      name: "Inside Sin",
      key: "23",
      image: "/images/Inside_Sin.jpg",
      image_height: 400,
      image_width: 521,
      description:
        "A mysterious space overflowing with pyreflies that unfolds within Sin's massive body. The existence of realms resembling Dream Zanarkand and a blitzball stadium are reflections of Jecht's memories influencing Sin.",
    },
    {
      name: "Omega Ruins",
      key: "24",
      image: "/images/Omega_Ruins.jpg",
      image_height: 400,
      image_width: 712,
      description:
        "An optional dungeon located within a small group of islands to the east of Spira's main continent. You can access this area through the monster arena. Rather maze-like, like inside Sin, this place must be mapped by the player. Navigating the dark passages you encounter Master Tonberry and Great Malboro, some of the toughest fiends in Spira. You face off two bosses at the end, Omega and Ultima.",
    },
  ],
  players: [
    {
      teamname: "Besaid Aurochs",
      key: "1",
      image: "/images/Tidus_blitzball.webp",
      image_height: 200,
      image_width: 72,
      name: "Tidus",
      techniques: "Venom Tackle, Drain Tackle, Anti-Venom 2",
      location: "N/A",
    },
    {
      teamname: "Besaid Aurochs",
      key: "2",
      image: "/images/Datto.webp",
      image_height: 200,
      image_width: 87,
      name: "Datto",
      techniques: "Wither Shot, Anti-Venom, Wither Shot 2",
      location: "Luca Stadium - Aurochs Locker Room",
    },
    {
      teamname: "Besaid Aurochs",
      key: "3",
      image: "/images/Letty.webp",
      image_height: 200,
      image_width: 60,
      name: "Letty",
      techniques: "Wither Tackle, Nap Pass, Venom Pass 3",
      location: "Luca Stadium - Aurochs Locker Room",
    },
    {
      teamname: "Besaid Aurochs",
      key: "4",
      image: "/images/Jassu.webp",
      image_height: 200,
      image_width: 91,
      name: "Jassu",
      techniques: "Wither Tackle, Wither Tackle 2, Nap Tackle 2",
      location: "Luca Stadium - Aurochs Locker Room",
    },
    {
      teamname: "Besaid Aurochs",
      key: "5",
      image: "/images/Botta.webp",
      image_height: 200,
      image_width: 75,
      name: "Botta",
      techniques: "Venom Shot, Venom Pass 2, Nap Tackle",
      location: "Luca Stadium - Aurochs Locker Room",
    },
    {
      teamname: "Besaid Aurochs",
      key: "6",
      image: "/images/Keepa.webp",
      image_height: 200,
      image_width: 87,
      name: "Keepa",
      techniques: "Super Goalie, Volley Shoot, Anti-Wither",
      location: "Luca Stadium - Aurochs Locker Room",
    },
    {
      teamname: "Kilika Beasts",
      key: "1",
      image: "/images/Larbeight.jpg",
      image_height: 200,
      image_width: 74,
      name: "Larbeight",
      techniques: "Wither Shot, Anit-Nap, Tackle Slip 2",
      location: "Kilika Port - Docks",
    },
    {
      teamname: "Kilika Beasts",
      key: "2",
      image: "/images/Isken.jpg",
      image_height: 200,
      image_width: 78,
      name: "Isken",
      techniques: "Wither Pass, Wither Tackle, Wither Tackle 2",
      location: "Kilika Port - House",
    },
    {
      teamname: "Kilika Beasts",
      key: "3",
      image: "/images/Vuroja.jpg",
      image_height: 200,
      image_width: 95,
      name: "Vuroja",
      techniques: "Wither Tackle, Nap Pass, Anti-Nap",
      location: "Kilika Port - Docks",
    },
    {
      teamname: "Kilika Beasts",
      key: "4",
      image: "/images/Kulukan.webp",
      image_height: 200,
      image_width: 80,
      name: "KuluKan",
      techniques: "Drain Tackle, Nap Pass, Venom Tackle 3",
      location: "Kilika Port - Tavern",
    },
    {
      teamname: "Kilika Beasts",
      key: "5",
      image: "/images/Deim.webp",
      image_height: 200,
      image_width: 56,
      name: "Deim",
      techniques: "Venom Tackle, Wither Pass, Pile Wither",
      location: "Kilika Port - Great Hall",
    },
    {
      teamname: "Kilika Beasts",
      key: "6",
      image: "/images/Nizarut.webp",
      image_height: 200,
      image_width: 70,
      name: "Nizarut",
      techniques: "Venom Shot, Anti-Wither, Anti-Nap",
      location: "Kilika Port - Great Hall",
    },
    {
      teamname: "Luca Goers",
      key: "1",
      image: "/images/Bickson.webp",
      image_height: 200,
      image_width: 89,
      name: "Bickson",
      techniques: "Wither Shot, Nap Pass, Anti-Nap",
      location: "Luca Harbor - Number 3 Dock",
    },
    {
      teamname: "Luca Goers",
      key: "2",
      image: "/images/Abus.webp",
      image_height: 200,
      image_width: 64,
      name: "Abus",
      techniques: "Grip Gloves, Venom Tackle 2, Venom Shot 3",
      location: "Luca Harbor - Number 3 Dock",
    },
    {
      teamname: "Luca Goers",
      key: "3",
      image: "/images/Graav.webp",
      image_height: 200,
      image_width: 92,
      name: "Graav",
      techniques: "Venom Pass, Tackle Slip, Drain Tackle 2",
      location: "Luca Harbor - Number 3 Dock",
    },
    {
      teamname: "Luca Goers",
      key: "4",
      image: "/images/Doram.webp",
      image_height: 200,
      image_width: 93,
      name: "Doram",
      techniques: "Wither Tackle, Nap Tackle, Volley Shot",
      location: "Luca Harbor - Number 3 Dock",
    },
    {
      teamname: "Luca Goers",
      key: "5",
      image: "/images/Balgerda.webp",
      image_height: 200,
      image_width: 52,
      name: "Balgerda",
      techniques: "Nap Tackle, Anti-Wither, Drain Tackle",
      location: "Luca Harbor - Number 3 Dock",
    },
    {
      teamname: "Luca Goers",
      key: "6",
      image: "/images/Raudy.jpg",
      image_height: 200,
      image_width: 67,
      name: "Raudy",
      techniques: "Grip Gloves, Gamble, Tackle Slip 2",
      location: "Luca Harbor - Number 3 Dock",
    },
    {
      teamname: "Al Bhed Psyches",
      key: "1",
      image: "/images/Eigaar.webp",
      image_height: 200,
      image_width: 70,
      name: "Eigaar",
      techniques: "Venom Tackls, Spin Ball, Volley Shot 3",
      location: "Airship - Corridor",
    },
    {
      teamname: "Al Bhed Psyches",
      key: "2",
      image: "/images/Blappa.webp",
      image_height: 200,
      image_width: 61,
      name: "Blappa",
      techniques: "Elite Defense, Drain Tackle, Nap Shot",
      location: "Airship - Corridor",
    },
    {
      teamname: "Al Bhed Psyches",
      key: "3",
      image: "/images/Berrik.webp",
      image_height: 200,
      image_width: 93,
      name: "Berrik",
      techniques: "Venom Tackle, Wither Tackle 2, Elite Defense",
      location: "Airship - Corridor",
    },
    {
      teamname: "Al Bhed Psyches",
      key: "4",
      image: "/images/Judda.webp",
      image_height: 200,
      image_width: 84,
      name: "Judda",
      techniques: "Anti-Nap, Wither Tackle, Anti-Wither",
      location: "Airship - Corridor",
    },
    {
      teamname: "Al Bhed Psyches",
      key: "5",
      image: "/images/Lakkam.webp",
      image_height: 200,
      image_width: 51,
      name: "Lakkam",
      techniques: "Venom Tackle, Nap Pass, Tackle Slip",
      location: "Airship - Corridor",
    },
    {
      teamname: "Al Bhed Psyches",
      key: "6",
      image: "/images/Nimrook.webp",
      image_height: 200,
      image_width: 62,
      name: "Nimrook",
      techniques: "Vemon Tackle, Venom Tackle 2, Anti-Drain",
      location: "Airship - Corridor",
    },
    {
      teamname: "Guado Glories",
      key: "1",
      image: "/images/Giera.webp",
      image_height: 200,
      image_width: 63,
      name: "Giera Guado",
      techniques: "Venom Shot, Nap Shot, Pile Venom",
      location: "Guadosalam",
    },
    {
      teamname: "Guado Glories",
      key: "2",
      image: "/images/Zazi.webp",
      image_height: 200,
      image_width: 62,
      name: "Zazi Guado",
      techniques: "Anti-Venom, Wither Shot 2, Anti-Venom 2",
      location: "Guadosalam - House",
    },
    {
      teamname: "Guado Glories",
      key: "3",
      image: "/images/Nav.webp",
      image_height: 200,
      image_width: 89,
      name: "Navara Guado",
      techniques: "Drain Tackle, Super Goalie, Nap Tackle 2",
      location: "Guadosalam",
    },
    {
      teamname: "Guado Glories",
      key: "4",
      image: "/images/Auda.webp",
      image_height: 200,
      image_width: 81,
      name: "Auda Guado",
      techniques: "Anit-Venom, Anti-Nap, Anti-Wither",
      location: "Guadosalam",
    },
    {
      teamname: "Guado Glories",
      key: "5",
      image: "/images/Pah.webp",
      image_height: 200,
      image_width: 59,
      name: "Pah Guado",
      techniques: "Drain Tackle, Venom Tackle 2, Gamble",
      location: "Guadosalam - House",
    },
    {
      teamname: "Guado Glories",
      key: "6",
      image: "/images/Noy.webp",
      image_height: 200,
      image_width: 90,
      name: "Noy Guado",
      techniques: "Anti-Nap, Wither Pass 2, Elite Defense",
      location: "Guadosalam - Inn",
    },
    {
      teamname: "Ronso Fangs",
      key: "1",
      image: "/images/Basik.jpg",
      image_height: 200,
      image_width: 95,
      name: "Basik Ronso",
      techniques: "Nap Shot, Venom Tackle, Invisible Shot",
      location: "Luca Harbor - Number 4 Dock",
    },
    {
      teamname: "Ronso Fangs",
      key: "2",
      image: "/images/Argai.jpg",
      image_height: 200,
      image_width: 92,
      name: "Argai Ronso",
      techniques: "Wither Tackle, Venom Pass 2, Anti-Drain",
      location: "Luca Harbor - Number 4 Dock",
    },
    {
      teamname: "Ronso Fangs",
      key: "3",
      image: "/images/Gazna.jpg",
      image_height: 200,
      image_width: 90,
      name: "Gazna Ronso",
      techniques: "Venom Pass, Drain Tackle, Volley Shot 2",
      location: "Luca Harbor - Number 4 Dock",
    },
    {
      teamname: "Ronso Fangs",
      key: "4",
      image: "/images/Nuvy.jpg",
      image_height: 200,
      image_width: 60,
      name: "Nuvy Ronso",
      techniques: "Venom Tackle, Volleyh Shot, Tackle Slip",
      location: "Luca Harbor - Number 4 Dock",
    },
    {
      teamname: "Ronso Fangs",
      key: "5",
      image: "/images/Irga.webp",
      image_height: 200,
      image_width: 61,
      name: "Irga Ronso",
      techniques: "Venom Shot, Anti-Venom, Anti-Wither",
      location: "Luca Harbor - Number 4 Dock",
    },
    {
      teamname: "Ronso Fangs",
      key: "6",
      image: "/images/Zamzi.jpg",
      image_height: 200,
      image_width: 88,
      name: "Zamzi Ronso",
      techniques: "Venom Pass, Wither Shot, Wither Pass",
      location: "Luca Harbor - Number 4 Dock",
    },
  ],
});

export const get_name_by_character = (role) => {
  return data.characters
    .filter((character) => character.role === role)
    .sort((a, b) => a.key - b.key);
};

export const get_character_by_role = (role) => {
  return data.characters.filter((character) => character.role === role).at(0);
};

export const get_players_by_teamname = (teamname) => {
  return data.players
    .filter((player) => player.teamname === teamname)
    .sort((a, b) => a.key - b.key);
};

export const get_team_by_teamname = (teamname) => {
  return data.players.filter((team) => team.name == teamname).at(0);
};
