export const data = Object.freeze({
  characters: [
    {
      teamname: "Besaid Aurochs",
      key: "1",
      image: "/images/Tidus_blitzball.webp",
      image_height: 200,
      image_width: 72,
      name: "Tidus",
      techniques: "Venom Tackle, Drain Tackle, Anti-Venom 2",
      location: "N/A",
    },
    {
      teamname: "Besaid Aurochs",
      key: "2",
      image: "/images/Datto.webp",
      image_height: 200,
      image_width: 87,
      name: "Datto",
      techniques: "Wither Shot, Anti-Venom, Wither Shot 2",
      location: "Luca Stadium - Aurochs Locker Room",
    },
    {
      teamname: "Besaid Aurochs",
      key: "3",
      image: "/images/Letty.webp",
      image_height: 200,
      image_width: 60,
      name: "Letty",
      techniques: "Wither Tackle, Nap Pass, Venom Pass 3",
      location: "Luca Stadium - Aurochs Locker Room",
    },
    {
      teamname: "Besaid Aurochs",
      key: "4",
      image: "/images/Jassu.webp",
      image_height: 200,
      image_width: 91,
      name: "Jassu",
      techniques: "Wither Tackle, Wither Tackle 2, Nap Tackle 2",
      location: "Luca Stadium - Aurochs Locker Room",
    },
    {
      teamname: "Besaid Aurochs",
      key: "5",
      image: "/images/Botta.webp",
      image_height: 200,
      image_width: 75,
      name: "Botta",
      techniques: "Venom Shot, Venom Pass 2, Nap Tackle",
      location: "Luca Stadium - Aurochs Locker Room",
    },
    {
      teamname: "Besaid Aurochs",
      key: "6",
      image: "/images/Keepa.webp",
      image_height: 200,
      image_width: 87,
      name: "Keepa",
      techniques: "Super Goalie, Volley Shoot, Anti-Wither",
      location: "Luca Stadium - Aurochs Locker Room",
    },
    {
      teamname: "Kilika Beasts",
      key: "1",
      image: "/images/Larbeight.jpg",
      image_height: 200,
      image_width: 74,
      name: "Larbeight",
      techniques: "Wither Shot, Anit-Nap, Tackle Slip 2",
      location: "Kilika Port - Docks",
    },
    {
      teamname: "Kilika Beasts",
      key: "2",
      image: "/images/Isken.jpg",
      image_height: 200,
      image_width: 78,
      name: "Isken",
      techniques: "Wither Pass, Wither Tackle, Wither Tackle 2",
      location: "Kilika Port - House",
    },
    {
      teamname: "Kilika Beasts",
      key: "3",
      image: "/images/Vuroja.jpg",
      image_height: 200,
      image_width: 95,
      name: "Vuroja",
      techniques: "Wither Tackle, Nap Pass, Anti-Nap",
      location: "Kilika Port - Docks",
    },
    {
      teamname: "Kilika Beasts",
      key: "4",
      image: "/images/KuluKan.webp",
      image_height: 200,
      image_width: 80,
      name: "KuluKan",
      techniques: "Drain Tackle, Nap Pass, Venom Tackle 3",
      location: "Kilika Port - Tavern",
    },
    {
      teamname: "Kilika Beasts",
      key: "5",
      image: "/images/Deim.webp",
      image_height: 200,
      image_width: 56,
      name: "Deim",
      techniques: "Venom Tackle, Wither Pass, Pile Wither",
      location: "Kilika Port - Great Hall",
    },
    {
      teamname: "Kilika Beasts",
      key: "6",
      image: "/images/Nizarut.webp",
      image_height: 200,
      image_width: 70,
      name: "Nizarut",
      techniques: "Venom Shot, Anti-Wither, Anti-Nap",
      location: "Kilika Port - Great Hall",
    },
  ],
});

export const get_characters_by_teamname = (teamname) => {
  return data.characters
    .filter((character) => character.teamname === teamname)
    .sort((a, b) => a.key - b.key);
};

export const get_team_by_teamname = (teamname) => {
  return data.characters.filter((team) => team.name == teamname).at(0);
};
